backend:
  name: github
  repo: danielgovan/gatsby-gallery-site
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "words"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/words"
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path, default: "/words/{{title}}/words" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
